--LISTAR NOME DOS USUARIOS, INFORMAR SEXO,CASADOS, QUE RESIDEM EM CARUARU E ESTÃO ATIVOS
SELECT DISTINCT U.NM_SEGURADO,
                U.TP_SEXO,
                U.TP_ESTADO_CIVIL,
                U.SN_ATIVO,
                C.DS_ENDERECO_COBRANCA,
                C.DS_BAIRRO,
                C.NM_CIDADE,
                C.NM_UF
  FROM DBAPS.USUARIO U
 INNER JOIN DBAPS.CONTRATO C
    ON U.CD_MATRICULA = C.CD_MATRICULA
 WHERE U.TP_ESTADO_CIVIL = 'C'
   AND C.NM_CIDADE = 'CARUARU'
   AND U.SN_ATIVO = 'S'
   ORDER BY U.NM_SEGURADO ASC
