SELECT P.NM_PRESTADOR,P.CD_PRESTADOR, COUNT(P.NM_PRESTADOR) AS "CONSULTAS"
  FROM (DBAPS.V_CTAS_MEDICAS C INNER JOIN DBAPS.PRESTADOR P ON
        C.CD_PRESTADOR = P.CD_PRESTADOR)
 INNER JOIN DBAPS.USUARIO U
    ON C.CD_MATRICULA = U.CD_MATRICULA
 WHERE C.DT_COMPETENCIA = '202206'
   AND P.NM_PRESTADOR != '0'
   AND U.SN_ATIVO = 'S'
 GROUP BY P.NM_PRESTADOR
 ORDER BY P.NM_PRESTADOR ASC
